[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 6
